---

# RHEL/CentOS 7 and 8 include firewalld by default
# This naively adds ports if the service is running and enabled

- name: Get service facts
  ansible.builtin.service_facts:

- name: CentOS - Open 4000 through 4006/tcp if firewalld is running and enabled
  ansible.posix.firewalld:
    port: 4000-4006/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: (ansible_os_family == 'RedHat') and (ansible_facts.services['firewalld.service'].state == "running" and ansible_facts.services['firewalld.service'].status == "enabled") 

- name: CentOS - Open 27017/tcp for MongoDB if firewalld is running and enabled
  ansible.posix.firewalld:
    port: 27017/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: (ansible_os_family == 'RedHat') and (ansible_facts.services['firewalld.service'].state == "running" and ansible_facts.services['firewalld.service'].status == "enabled") 

- name: Ubuntu - Open 4000 through 4006/tcp if UFW is running and enabled
  community.general.ufw:
    rule: allow
    port: 4000-4006
    proto: tcp
  when: (ansible_os_family == 'Debian') and (ansible_facts.services['ufw.service'].state == "running") and (ansible_facts.services['ufw.service'].status == "enabled")

- name: Ubuntu - Open 27017/tcp for MongoDB if UFW is running and enabled
  community.general.ufw:
    rule: allow
    port: 27017
    proto: tcp
  when: (ansible_os_family == 'Debian') and (ansible_facts.services['ufw.service'].state == "running") and (ansible_facts.services['ufw.service'].status == "enabled")