---

- name: CentOS - Install NVMesh Packages
  package:
    name:
      - nvmesh-utils
      - nvmesh-core
    state: installed
  when: ansible_os_family == 'RedHat'

- name: Debian - Download NVMesh Utils deb file
  get_url:
    url: "https://repo.excelero.com/nvmesh/2.4.1/ubuntu/20.04/x86_64/nvmesh-utils_2.4.1-17.ubuntu2004_amd64.deb"
    dest: "/tmp"
    username: "{{ nvmesh_repo_username }}"
    password: "{{ nvmesh_repo_password }}"
  when: ansible_os_family == 'Debian'

- name: Debian - Download NVMesh Core deb file
  get_url:
    url: "https://repo.excelero.com/nvmesh/2.4.1/ubuntu/20.04/x86_64/nvmesh-core_2.4.1-53.ubuntu2004_amd64.deb"
    dest: "/tmp"
    username: "{{ nvmesh_repo_username }}"
    password: "{{ nvmesh_repo_password }}"
  when: ansible_os_family == 'Debian'

- name: "Debian - Install NVMesh Utils"
  apt:
    deb: /tmp/nvmesh-utils_2.4.1-17.ubuntu2004_amd64.deb
  when: ansible_os_family == 'Debian'

- name: "Debian - Install NVMesh Core"
  apt:
    deb: /tmp/nvmesh-core_2.4.1-53.ubuntu2004_amd64.deb
  when: ansible_os_family == 'Debian'

# TODO: potentially explicitly include the dependencies